### ISSUE TITLE
Add "linear" function

### ISSUE THREAD

**Issue by gpulido** [semitable/easing-functions#1]
Hello,
Thanks for the library it is very helpfull.
I would like to incorporate a "linear function" just for the cases where a linear animation is needed.  It as simple as:
```python
class LinearInOut(EasingBase):
  def func(self, t):
      return t
```
I tried to just extend it on my code but the EasingBase class is not exposed.
So would you mind either adding the linear funct, either adding the easingbase to the exported classes so it can be extended? 
I can make a pr for you if you prefer it.
Thank you in advance!!
Gabriel

**Comment by semitable** [comment]
Hi @gpulido,
I did add it as "LinearInOut" and bumped the version so that you can upgrade via pip.

Best,
Filippos
